# 身份标识配置
identity:
  # 教师身份关键词
  teacher: ['教师', '老师', '指导教师', '指导老师']
  # 学生身份关键词
  student: ['学生', '队长', '队员', '学']

# 文本格式化配置
formatting:
  # 教师和学生输出信息格式
  output_pattern_teacher: '{institution}-{name}（教师）'
  output_pattern_student: '{institution}-{name}'
  # 连接符和分隔符
  connectors: [
    ' ', '-', '_', '—', '－', '–', '+', '/',
    '~', '～', '(', ')', '（', '）', '。',
    '丶', '，', '、', '；', ';', '：', ':'
  ]
  # 是否包含二级学院
  include_secondary_college: false

# 机构相关配置
institution:
  # 机构后缀关键词
  suffixes: [
    '大学', '学院', '学校', '系',
    '工大', '理工', '师大', '交大', '科大', '农大', '医大',
    '财大', '外院', '美院', '体院', '艺院', '电院', '财经',
    '职业技术学院', '理工学院', '师范学院', '师范', '幼儿师范',
    '专科学校',
  ]
  # 机构简称
  shortened_names: [
    '河工大', '洛理', '哈理工', '商科院', '林建', '河财金', '洛科', '吉财', '华水', '新工', '河大',
    '郑航',
  ]
  # 排除的关键词
  excluded_keywords: [
    '学院路', '语学', '大学人文',
  ]
  # 默认机构名称
  default_name: '未知机构'

# 姓名相关配置
name:
  # 默认姓名
  default_name: '无名无姓'